#!/usr/bin/env python3
"""
Synthesize a behavioral profile from extracted session messages.

Uses `claude --print` for multi-pass LLM synthesis — no API key needed.

Usage:
    python3 scripts/synthesize-profile.py /tmp/imprint-messages.json [--passes N] [--model MODEL]
"""

import json
import random
import subprocess
import sys
import textwrap
from pathlib import Path


PROFILE_PATH = Path.home() / ".claude" / ".imprint"
TEMPLATE_DIR = Path(__file__).parent.parent / "templates"

# Max messages per synthesis batch to stay within context limits
BATCH_SIZE = 150

# Max synthesis passes — merging too many partial profiles degrades quality
MAX_AUTO_PASSES = 10

# Max message length for synthesis (truncate longer messages)
MAX_MSG_LEN = 500

# Timeout per claude --print call (seconds)
CLAUDE_TIMEOUT = 1200


def load_messages(input_path: Path) -> dict:
    data = json.loads(input_path.read_text())
    return data


def load_template() -> str:
    template_path = TEMPLATE_DIR / "synthesis-prompt.md"
    return template_path.read_text()


def deduplicate_messages(messages: list[dict]) -> list[dict]:
    """Deduplicate and truncate messages for cleaner synthesis."""
    seen = set()
    cleaned = []
    for msg in messages:
        text = msg["text"].strip()
        if text in seen:
            continue
        seen.add(text)
        if len(text) > MAX_MSG_LEN:
            text = text[:MAX_MSG_LEN] + "..."
        cleaned.append({"text": text, "project": msg.get("project", "unknown")})
    return cleaned


def sample_messages(messages: list[dict], batch_size: int = BATCH_SIZE) -> list[list[dict]]:
    """Split messages into batches after shuffling for project diversity."""
    if len(messages) <= batch_size:
        return [messages]

    random.seed(42)
    shuffled = list(messages)
    random.shuffle(shuffled)

    batches = []
    for i in range(0, len(shuffled), batch_size):
        batches.append(shuffled[i:i + batch_size])

    return batches


def run_synthesis_pass(template: str, messages: list[dict], pass_label: str, model: str) -> str:
    """Run a single synthesis pass using claude --print with system prompt override."""
    message_text = "\n\n---\n\n".join(
        f"[Project: {m.get('project', 'unknown')}]\n{m['text']}"
        for m in messages
    )

    system_prompt = template + (
        "\n\nIMPORTANT: Output a COMPLETE structured behavioral profile with all sections "
        "filled out. Do NOT summarize or describe what you would do — actually produce the "
        "full profile document. Each section should have specific, actionable observations "
        "with supporting evidence."
    )

    user_prompt = f"Here are the user messages to analyze:\n\n{message_text}"

    print(f"  Running {pass_label} ({len(messages)} messages)...", flush=True)

    try:
        result = subprocess.run(
            [
                "claude", "--print",
                "--model", model,
                "--system-prompt", system_prompt,
                "-p", user_prompt,
            ],
            capture_output=True,
            text=True,
            timeout=CLAUDE_TIMEOUT,
        )
    except subprocess.TimeoutExpired:
        print(f"  TIMEOUT on {pass_label}", file=sys.stderr, flush=True)
        return ""

    if result.returncode != 0:
        print(f"  Warning: {pass_label} returned code {result.returncode}", file=sys.stderr, flush=True)
        if result.stderr:
            print(f"  stderr: {result.stderr[:300]}", file=sys.stderr, flush=True)

    out = result.stdout.strip()
    print(f"  -> {len(out)} chars", flush=True)
    return out


def run_merge_pass(partial_profiles: list[str], metadata: dict, model: str) -> str:
    """Merge multiple partial profiles into a final one."""
    system_prompt = textwrap.dedent(f"""\
        You are merging multiple partial behavioral profiles into a single coherent profile.

        Each partial profile was generated from a different batch of the same user's session history.
        Combine them into one unified profile, deduplicating insights and strengthening patterns
        that appear across multiple batches.

        Metadata:
        - Sessions analyzed: {metadata['session_count']}
        - Total messages: {metadata['message_count']}

        Rules:
        - Merge duplicate observations into single stronger statements
        - If a pattern appears in multiple batches, increase confidence
        - Resolve contradictions by favoring the more specific observation
        - Keep the same section structure as the input profiles
        - Start the file with: # User Behavioral Profile
        - Include metadata: > Auto-generated by imprint | {metadata['session_count']} sessions | {metadata['message_count']} messages
        - Mark observations with [low confidence] if they only appeared in one batch
        - CRITICAL: Output the FULL merged profile with ALL sections and ALL observations.
          Do NOT output a summary of changes or describe the merge process.
          The output must be a complete, standalone behavioral profile document ready to be saved to a file.
    """)

    user_prompt = "## Partial Profiles\n\n"
    for i, profile in enumerate(partial_profiles):
        user_prompt += f"### Batch {i + 1}\n\n{profile}\n\n"

    print(f"  Running merge pass ({len(partial_profiles)} batches)...", flush=True)

    try:
        result = subprocess.run(
            [
                "claude", "--print",
                "--model", model,
                "--system-prompt", system_prompt,
                "-p", user_prompt,
            ],
            capture_output=True,
            text=True,
            timeout=CLAUDE_TIMEOUT,
        )
    except subprocess.TimeoutExpired:
        print("  TIMEOUT on merge pass", file=sys.stderr, flush=True)
        return ""

    out = result.stdout.strip()
    print(f"  -> {len(out)} chars", flush=True)
    return out


def main():
    import argparse

    parser = argparse.ArgumentParser(description="Synthesize behavioral profile")
    parser.add_argument("input", help="Path to extracted messages JSON")
    parser.add_argument("--passes", type=int, default=0, help="Override number of passes (0 = auto, capped at %d)" % MAX_AUTO_PASSES)
    parser.add_argument("--model", default="sonnet", help="Claude model to use (default: sonnet)")
    parser.add_argument("--timeout", type=int, default=0, help="Timeout per claude --print call in seconds (0 = use default)")
    args = parser.parse_args()

    if args.timeout > 0:
        global CLAUDE_TIMEOUT
        CLAUDE_TIMEOUT = args.timeout

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: {input_path} not found", file=sys.stderr)
        sys.exit(1)

    data = load_messages(input_path)
    messages = data["messages"]
    metadata = {
        "session_count": data["session_count"],
        "message_count": data["message_count"],
    }

    print(f"Loaded {len(messages)} messages from {metadata['session_count']} sessions", flush=True)

    # Deduplicate and truncate
    messages = deduplicate_messages(messages)
    metadata["message_count"] = len(messages)
    print(f"After dedup/truncation: {len(messages)} unique messages", flush=True)

    # Remove existing profile to prevent contamination via CLAUDE.md
    if PROFILE_PATH.exists():
        PROFILE_PATH.unlink()
        print("Removed existing profile to prevent contamination", flush=True)

    template = load_template()
    batches = sample_messages(messages)
    num_passes = args.passes if args.passes > 0 else min(len(batches), MAX_AUTO_PASSES)

    print(f"Running {num_passes} synthesis pass(es)...", flush=True)

    partial_profiles = []
    for i, batch in enumerate(batches[:num_passes]):
        profile = run_synthesis_pass(template, batch, f"pass {i + 1}/{num_passes}", args.model)
        if profile:
            partial_profiles.append(profile)

    if not partial_profiles:
        print("Error: All synthesis passes failed", file=sys.stderr)
        sys.exit(1)

    # If multiple batches, merge them
    if len(partial_profiles) > 1:
        final_profile = run_merge_pass(partial_profiles, metadata, args.model)
    else:
        final_profile = partial_profiles[0]

    if not final_profile:
        print("Error: Final profile is empty", file=sys.stderr)
        sys.exit(1)

    # Ensure header exists
    if not final_profile.startswith("# "):
        final_profile = (
            f"# User Behavioral Profile\n\n"
            f"> Auto-generated by imprint on {__import__('datetime').datetime.now().strftime('%Y-%m-%d')}\n"
            f"> Based on {metadata['session_count']} sessions ({metadata['message_count']} messages)\n"
            f"> Edit this file to correct or refine the profile.\n\n"
            + final_profile
        )

    PROFILE_PATH.parent.mkdir(parents=True, exist_ok=True)
    PROFILE_PATH.write_text(final_profile)
    print(f"\nProfile written to {PROFILE_PATH}", flush=True)
    print(f"  Lines: {len(final_profile.splitlines())}", flush=True)


if __name__ == "__main__":
    main()
